#!/bin/bash

sleep 5

redis-cli<<EOF

HSET E102 code "E102" name "Tartrazine" desc "May cause allergic reactions and hyperactivity in children."
HSET E104 code "E104" name "Quinoline Yellow" desc "Suspected of causing allergic reactions and asthma."
HSET E110 code "E110" name "Sunset Yellow FCF" desc "May cause hyperactivity and allergic reactions."
HSET E120 code "E120" name "Carminic Acid" desc "Sometimes causes allergic reactions in sensitive individuals."
HSET E122 code "E122" name "Azorubine" desc "Known to cause allergic reactions and concentration problems in children."
HSET E123 code "E123" name "Amaranth" desc "Suspected of having carcinogenic properties, banned in the USA."
HSET E124 code "E124" name "Ponceau 4R (Cochineal Red A)" desc "Linked to allergies and a potential increase in ADHD risk."
HSET E127 code "E127" name "Erythrosine" desc "Associated with thyroid disorders and hyperactivity in studies."
HSET E128 code "E128" name "Red 2G" desc "Suspected to have carcinogenic effects, banned in several countries."
HSET E129 code "E129" name "Allura Red AC" desc "May cause allergic reactions and hyperactivity."
HSET E131 code "E131" name "Patent Blue V" desc "May cause allergic reactions and blood pressure problems."
HSET E132 code "E132" name "Indigo Carmine" desc "May cause allergic reactions and stomach issues."
HSET E133 code "E133" name "Brilliant Blue FCF" desc "Linked to hyperactivity and concentration problems in children."
HSET E142 code "E142" name "Green S" desc "May cause stomach problems and allergies."
HSET E150 code "E150" name "Ammonium Caramel" desc "Suspected of having carcinogenic properties at high doses."
HSET E151 code "E151" name "Brilliant Black BN" desc "May cause allergies and hyperactivity."
HSET E154 code "E154" name "Brown FK" desc "Suspected of carcinogenic effects and allergies, banned in several countries."
HSET E155 code "E155" name "Brown HT" desc "May cause allergic reactions and hyperactivity."
HSET E160b code "E160b" name "Annatto (Bixin, Norbixin)" desc "Known to cause allergic reactions in sensitive individuals."
HSET E173 code "E173" name "Aluminium" desc "Can accumulate in the body and lead to nervous system damage."
HSET E180 code "E180" name "Litholrubine BK" desc "May cause allergic reactions and skin problems."
HSET E210 code "E210" name "Benzoic Acid" desc "May cause allergic reactions, especially in people with asthma, and is suspected of being carcinogenic with long-term consumption."
HSET E211 code "E211" name "Sodium Benzoate" desc "Linked to hyperactivity in children and a potential risk of allergic reactions and asthma."
HSET E212 code "E212" name "Potassium Benzoate" desc "May cause irritation and allergic reactions; considered potentially carcinogenic when combined with Vitamin C."
HSET E213 code "E213" name "Calcium Benzoate" desc "Like other benzoates, may cause allergic reactions and affect concentration."
HSET E214 code "E214" name "Ethylparaben" desc "Known to cause allergic reactions and potential hormonal disturbances."
HSET E215 code "E215" name "Sodium Ethylparaben" desc "May cause allergic reactions and is linked to hormonal disturbances."
HSET E216 code "E216" name "Propylparaben" desc "Suspected of causing allergic reactions and disrupting hormonal balance."
HSET E217 code "E217" name "Sodium Propylparaben" desc "May cause allergies and hormonal disturbances, especially in children."
HSET E218 code "E218" name "Methylparaben" desc "Linked to allergic reactions and potential effects on hormonal balance."
HSET E219 code "E219" name "Sodium Methylparaben" desc "May lead to allergic reactions and hormonal disruptions."
HSET E220 code "E220" name "Sulfur Dioxide" desc "May cause shortness of breath, especially in asthmatics, and irritate the digestive tract."
HSET E221 code "E221" name "Sodium Sulfite" desc "A known allergen that can cause shortness of breath and asthmatic reactions."
HSET E222 code "E222" name "Sodium Bisulfite" desc "May cause allergic reactions, shortness of breath, and stomach irritation."
HSET E223 code "E223" name "Sodium Metabisulfite" desc "Associated with allergic reactions, shortness of breath, and headaches."
HSET E224 code "E224" name "Potassium Metabisulfite" desc "May cause allergic reactions, stomach irritation, and asthmatic problems."
HSET E226 code "E226" name "Calcium Sulfite" desc "May cause digestive issues and allergies, especially in asthmatics."
HSET E227 code "E227" name "Calcium Bisulfite" desc "Linked to allergies and digestive tract irritations."
HSET E228 code "E228" name "Potassium Bisulfite" desc "Known to trigger asthmatic reactions and allergies."
HSET E230 code "E230" name "Biphenyl" desc "Used as a preservative but suspected of carcinogenic effects at high doses."
HSET E231 code "E231" name "Orthophenylphenol" desc "Known for its irritating properties and suspected carcinogenic effects."
HSET E232 code "E232" name "Sodium Orthophenylphenol" desc "May irritate the skin and respiratory tract."
HSET E235 code "E235" name "Natamycin" desc "May cause allergic reactions and can harm intestinal microflora."
HSET E239 code "E239" name "Hexamethylenetetramine" desc "May be toxic to the kidneys and cause allergic reactions."
HSET E249 code "E249" name "Potassium Nitrite" desc "Can form carcinogenic nitrosamines when combined with proteins."
HSET E250 code "E250" name "Sodium Nitrite" desc "Linked to cancer risk, especially when combined with proteins, and may cause shortness of breath."
HSET E251 code "E251" name "Sodium Nitrate" desc "May lead to the formation of carcinogenic compounds during heat treatment."
HSET E252 code "E252" name "Potassium Nitrate" desc "Like other nitrates, may lead to the formation of carcinogenic compounds."
HSET E284 code "E284" name "Boric Acid" desc "Toxic to the kidneys and nervous system; potentially dangerous with long-term consumption."
HSET E285 code "E285" name "Sodium Tetraborate (Borax)" desc "May irritate the digestive system and is potentially toxic when consumed in large amounts."
HSET E310 code "E310" name "Propyl Gallate" desc "An antioxidant used in fats, it may cause skin irritation, allergies, and stomach problems; linked to asthmatic reactions in some individuals."
HSET E320 code "E320" name "Butylated Hydroxyanisole (BHA)" desc "An antioxidant added to fats and oils, suspected of having carcinogenic properties and affecting hormonal functions at high doses."
HSET E321 code "E321" name "Butylated Hydroxytoluene (BHT)" desc "Similar to BHA, it is an antioxidant used in fat-containing products; suspected of having carcinogenic properties and being toxic to the endocrine system."
HSET E385 code "E385" name "Calcium Disodium EDTA (EDTA)" desc "A stabilizer and antioxidant used to preserve color and flavor, it may cause allergic reactions, and in excessive amounts, is toxic to the kidneys and liver, and can disrupt mineral absorption."
HSET E407 code "E407" name "Carrageenan" desc "A thickening agent and stabilizer that may cause stomach and intestinal issues; in large amounts, it is suspected of having pro-inflammatory properties and a negative impact on the digestive system."
HSET E421 code "E421" name "Mannitol" desc "A sweetener and bulking agent that can act as a laxative in excess and may cause gastrointestinal issues, especially in sensitive individuals."
HSET E432 code "E432" name "Polysorbate 20" desc "An emulsifier used in the food industry; it may cause allergic reactions, stomach problems, and hypersensitivity in allergic individuals."
HSET E433 code "E433" name "Polysorbate 80" desc "An emulsifier that can lead to gastrointestinal problems and is suspected of increasing intestinal permeability, potentially causing inflammation and allergies."
HSET E434 code "E434" name "Polysorbate 40" desc "An emulsifier that may cause intestinal irritation and allergic reactions, especially with long-term consumption."
HSET E435 code "E435" name "Polysorbate 60" desc "May cause digestive issues, including diarrhea, and may increase the risk of inflammatory conditions in the digestive tract for sensitive individuals."
HSET E436 code "E436" name "Polysorbate 65" desc "An emulsifier used in the food industry, similar to other polysorbates, it can trigger allergies and digestive problems when consumed in large amounts."
HSET E469 code "E469" name "Enzymatically Modified Cellulose" desc "A thickening agent that may cause digestive issues like bloating and gas, and in large quantities, it can have a laxative effect."
HSET E553b code "E553b" name "Talc (Magnesium Silicate)" desc "Used as an anti-caking agent and carrier in food products; may irritate the digestive tract when consumed in large amounts, and in dust form (when inhaled), it is classified as a potential carcinogen."
HSET E579 code "E579" name "Iron Gluconate" desc "A stabilizer primarily used in products containing olives; excessive consumption may cause digestive issues such as stomach pain, nausea, and vomiting, especially in individuals sensitive to iron."
HSET E621 code "E621" name "Monosodium Glutamate (MSG)" desc "A popular flavor enhancer used in snacks and ready-to-eat meals; in some individuals, it may cause the so-called 'Chinese Restaurant Syndrome,' which includes symptoms like headaches, excessive sweating, and a feeling of weakness."
HSET E622 code "E622" name "Potassium Glutamate" desc "A flavor enhancer similar to E621, used in low-sodium products; it may cause reactions similar to MSG, such as headaches, nausea, and digestive discomfort."
HSET E634 code "E634" name "Calcium Ribonucleotides" desc "A flavor enhancer often used alongside monosodium glutamate in snacks and meat products; it can exacerbate symptoms in individuals sensitive to MSG, such as headaches and stomach irritation."
HSET E635 code "E635" name "Disodium 5'-ribonucleotides" desc "A combination of disodium inosinate and disodium guanylate that enhances umami flavor; used in snacks and instant foods, it may trigger allergic reactions and stomach issues in sensitive individuals."
HSET E950 code "E950" name "Acesulfame K" desc "An intense sweetener used in low-calorie products; suspected to have carcinogenic effects and may impact metabolism, especially with prolonged consumption in large amounts."
HSET E951 code "E951" name "Aspartame" desc "A widely used sweetener found in diet drinks and products; it may cause headaches, dizziness, and is contraindicated for people with phenylketonuria (PKU) as it contains phenylalanine."
HSET E952 code "E952" name "Cyclamic Acid and Cyclamates (e.g., Sodium Cyclamate)" desc "A sweetener used in diet beverages; in high doses, it is suspected to have carcinogenic effects and is banned in some countries (e.g., the USA)."
HSET E954 code "E954" name "Saccharin" desc "An intense sweetener used in low-calorie products; it may leave a bitter aftertaste, and studies suggest a possible carcinogenic effect when consumed in large quantities."
HSET E962 code "E962" name "Aspartame-Acesulfame Salt" desc "A sweetener that combines aspartame and acesulfame K, used in reduced-calorie products; it may cause reactions similar to aspartame, such as headaches and digestive issues."
HSET E1201 code "E1201" name "Polyvinylpyrrolidone (PVP)" desc "A stabilizer and anti-caking agent also used in pharmaceuticals; in large quantities, it may affect kidney function and is difficult for the body to absorb."
HSET E1202 code "E1202" name "Crosslinked Polyvinylpyrrolidone (PVPP)" desc "Used as a stabilizer and clarifying agent in beverages (e.g., beer); consumption in large amounts may cause digestive problems and is not fully broken down in the body."
HSET E1520 code "E1520" name "Propylene Glycol" desc "It is a substance used as a carrier, solvent, and binder in the food, cosmetic, and pharmaceutical industries. In small amounts, it is considered safe, but excessive consumption can cause digestive issues, such as stomach pain and diarrhea. Additionally, sensitive individuals may experience allergic reactions or irritation of the skin and mucous membranes."

SAVE

EOF

echo "Redis initialized with sample data."